[package]
name = "cmfy"
version = "0.2.1-wip"
edition = "2021"
authors = ["Cédric Meuter <cedric.meuter@gmail.com>"]
description = "A CLI companion app for Comfy UI"
readme = "README.md"
license = "MIT"
keywords = ["comfy", "comfyui", "comfy-ui"]
homepage = "https://github.com/meuter/cmfy-rs"
repository = "https://github.com/meuter/cmfy-rs"

[lib]
name = "cmfy"
path = "src/lib/lib.rs"

[[bin]]
name = "cmfy"
path = "src/cli/main.rs"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive", "env"] }
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
colored = "2.1.0"
futures-util = "0.3.31"
http = "1.1.0"
humansize = "2.1.3"
humantime = "2.1.0"
itertools = "0.13.0"
open = "5.3.0"
range-parser = "0.1.2"
reqwest = "0.12.8"
ring = "0.17.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_urlencoded = "0.7.1"
size = "0.4.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tokio-websockets = { version = "0.10.1", features = ["client", "fastrand", "native-tls", "ring"] }
uuid = { version = "1.11.0", features = ["v4"] }
