[package]
name = "cmfy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "env"] }
reqwest = "0.12.8"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
