[package]
name = "cmfy"
version = "0.1.0"
edition = "2021"

[lib]
name = "cmfy"
path = "src/lib/lib.rs"

[[bin]]
name = "cmfy"
path = "src/cli/main.rs"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive", "env"] }
humansize = "2.1.3"
itertools = "0.13.0"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
size = "0.4.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
