[package]
name = "cmfy-nodes"
version = "0.3.0-wip"
edition = "2021"

[dependencies]
cmfy = { version = "0.3.0-wip", path = "../lib" }
cmfy-macros = { version = "0.3.0-wip", path = "../macros" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
