[package]
name = "cmfy-nodes"
version = "0.1.0"
edition = "2021"

[dependencies]
cmfy = { version = "0.1.0", path = "../lib" }
cmfy-macros = { version = "0.1.0", path = "../macros" }
serde = { version = "1.0.210", features = ["derive"] }
