name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build with default feature
        run: cargo build -r --workspace
      - name: Build examples
        run: cargo build -r --examples
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmfy-${{ matrix.os }}-${{ matrix.version }}
          path: target/release/cmfy*
